databases:
  - name: phase5
    databaseName: phase5
    user: phase5

services:
  - type: web
    name: phase5
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: phase5
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false